/**
 * scripts/fb-monitor/install.ts
 *
 *   npm run fb:install          # regenerate and load the scheduled jobs
 *   npm run fb:install -- --uninstall
 *
 * Generates one launchd job per region from groups.json and loads it, so the
 * schedule and the group lists have exactly one source of truth. Change an hour
 * or add a region in groups.json, re-run this, done.
 *
 * Replaces the earlier single com.mountainconnects.fbmonitor job, which is
 * unloaded and removed if present.
 *
 * NOTE ON LOCATION. The repo must live outside ~/Desktop, ~/Documents and
 * ~/Downloads. macOS TCC blocks background agents from those directories and a
 * launchd job cannot show a consent prompt, so it fails with "Operation not
 * permitted" before writing a single log line. This script refuses to install
 * from a protected path rather than let that happen silently.
 */
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import * as path from "node:path";

const REPO = process.cwd();
const AGENTS = path.join(homedir(), "Library", "LaunchAgents");
const LEGACY_LABEL = "com.mountainconnects.fbmonitor";
const LABEL_PREFIX = "com.mountainconnects.fbmonitor.";

type RegionConfig = { hour: number; postsPerGroup?: number; groups: string[] };

function fail(message: string): never {
  process.stderr.write(`\nfb-install: ${message}\n\n`);
  process.exit(1);
}

function launchctl(args: string[]): void {
  try {
    execFileSync("/bin/launchctl", args, { stdio: "pipe" });
  } catch {
    // unload of something not loaded is fine and common
  }
}

/**
 * Have a free local model decide which posts are worth paying to extract.
 *
 * Costs nothing and removes roughly a quarter of the paid calls. It reaches
 * Ollama over HTTP on localhost, so launchd's bare PATH does not matter, and
 * Ollama's own agent is RunAtLoad + KeepAlive so it is up whenever the user
 * is logged in. If it is not, triage sends everything and the run behaves
 * exactly as it did before — a missing local model can never empty the board.
 *
 * Set to false and re-run `npm run fb:install` to turn it off.
 */
const LOCAL_TRIAGE = true;

function plistFor(region: string, cfg: RegionConfig): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by scripts/fb-monitor/install.ts from groups.json — do not edit by
  hand; edit groups.json and re-run "npm run fb:install".

  Fires at ${String(cfg.hour).padStart(2, "0")}:00 local. run.sh adds up to 15 minutes of jitter, so
  the run lands somewhere in the following quarter hour. If the Mac is asleep,
  launchd runs the job once on wake rather than skipping or stacking it.
-->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${LABEL_PREFIX}${region}</string>

    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>${REPO}/scripts/fb-monitor/run.sh</string>
        <string>${region}</string>
    </array>

    <key>StartCalendarInterval</key>
    <array>
        <dict><key>Hour</key><integer>${cfg.hour}</integer><key>Minute</key><integer>0</integer></dict>
    </array>

    <key>WorkingDirectory</key>
    <string>${REPO}</string>

    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
        <key>HOME</key>
        <string>${homedir()}</string>
        <key>FB_LOCAL_TRIAGE</key>
        <string>${LOCAL_TRIAGE ? "1" : "0"}</string>
    </dict>

    <key>StandardOutPath</key>
    <string>${homedir()}/.mountain-connect/logs/launchd.${region}.out.log</string>
    <key>StandardErrorPath</key>
    <string>${homedir()}/.mountain-connect/logs/launchd.${region}.err.log</string>

    <key>RunAtLoad</key>
    <false/>
</dict>
</plist>
`;
}

function main(): void {
  const uninstall = process.argv.includes("--uninstall");

  const configPath = path.join(REPO, "scripts", "fb-monitor", "groups.json");
  if (!existsSync(configPath)) fail(`groups.json not found at ${configPath}`);

  const raw = JSON.parse(readFileSync(configPath, "utf8")) as Record<string, unknown>;
  const regions = Object.entries(raw).filter(([k]) => !k.startsWith("_")) as [string, RegionConfig][];

  mkdirSync(AGENTS, { recursive: true });
  mkdirSync(path.join(homedir(), ".mountain-connect", "logs"), { recursive: true });

  // Retire the pre-region single job if it is still around.
  const legacy = path.join(AGENTS, `${LEGACY_LABEL}.plist`);
  if (existsSync(legacy)) {
    launchctl(["unload", legacy]);
    rmSync(legacy);
    process.stderr.write(`  removed legacy job ${LEGACY_LABEL}\n`);
  }

  if (uninstall) {
    for (const [region] of regions) {
      const file = path.join(AGENTS, `${LABEL_PREFIX}${region}.plist`);
      if (existsSync(file)) {
        launchctl(["unload", file]);
        rmSync(file);
        process.stderr.write(`  removed ${LABEL_PREFIX}${region}\n`);
      }
    }
    process.stderr.write(`\nAll scheduled jobs removed.\n\n`);
    return;
  }

  // TCC guard — see the note at the top of this file.
  for (const protectedDir of ["Desktop", "Documents", "Downloads"]) {
    if (REPO.startsWith(path.join(homedir(), protectedDir))) {
      fail(
        `the repo is inside ~/${protectedDir}, which macOS blocks background agents from reading.\n\n` +
          `  A launchd job cannot prompt for consent, so it would fail with\n` +
          `  "Operation not permitted" before logging anything. Move the repo\n` +
          `  somewhere like ~/projects/ and re-run.`,
      );
    }
  }

  process.stderr.write(`\nrepo: ${REPO}\n\n`);

  for (const [region, cfg] of regions) {
    const file = path.join(AGENTS, `${LABEL_PREFIX}${region}.plist`);
    launchctl(["unload", file]);
    writeFileSync(file, plistFor(region, cfg), "utf8");
    launchctl(["load", file]);

    const count = new Set(cfg.groups ?? []).size;
    const note = count === 0 ? "  (no groups yet — will run and do nothing)" : "";
    process.stderr.write(
      `  ${LABEL_PREFIX}${region}`.padEnd(46) +
        `${String(cfg.hour).padStart(2, "0")}:00   ${String(count).padStart(2)} group(s)${note}\n`,
    );
  }

  process.stderr.write(`\nLoaded. Check with:  launchctl list | grep fbmonitor\n`);
  process.stderr.write(`Run one now with:    launchctl start ${LABEL_PREFIX}japan\n\n`);
}

main();
