-- 00110 — give every importable listing a category
--
-- `job_posts.category` was empty on 356 of 391 rows (354 of 355 OPEN ones);
-- the single value present was "Maintenance". Nothing ever wrote it for
-- imported listings, and imports are 349 of the open board.
--
-- ⚠️ IT LOOKED FINE, which is why it lasted. /jobs maps a blank to "Other"
-- in its view model, so the board's category filter rendered and offered
-- exactly two options — "Maintenance" and "Other" — for 355 jobs. A filter
-- that cannot filter is worse than no filter: a worker reads it as "there
-- are no chef jobs here".
--
-- ⚠️ THE ids AND CATEGORIES BELOW WERE GENERATED BY `categoryForTitle` IN
-- lib/jobs/category.ts — the same function the import route now calls — so a
-- title classified here and the same title classified on the next scrape
-- cannot disagree. Regenerate rather than hand-edit.
--
-- 350 of the 356 are classifiable. The remaining 6 are left NULL on purpose:
-- "Team Member", "Support Staff", "Dental Assistant" and the like carry no
-- signal, and NULL means "could not classify" where "Other" would mean
-- "classified as miscellaneous". Only the first is a rule worth adding later.
--
-- Guarded on `category IS NULL`, so a value set by hand in the admin form or
-- chosen by a business is never overwritten and a re-run is a no-op.

BEGIN;

CREATE TEMP TABLE _cat_before ON COMMIT DROP AS
  SELECT id, category, title FROM job_posts;

UPDATE job_posts SET category = 'Administration'
 WHERE category IS NULL AND id IN (
   '908e454f-c687-45a2-a775-f55137c11e72',
   'a81ebbaf-29a8-4aed-b1bc-d6ff73d0793f',
   '5ccb7bdc-090b-49a8-ac8a-e0c5afc03190',
   '936499b2-090b-4455-b7a1-187ba538fe9d',
   '546f9f2f-ad4e-49ed-8909-a3cf36bb45fa',
   'c5a53040-ea47-49f9-9a23-bb53a0110432',
   'ae6f26e4-306b-4367-bf35-37bb0610a47d',
   '88f9097b-6709-4507-b949-390fc3acbdbb',
   'f84215b0-85d0-44b2-b081-fd51f91740a6'
 );

UPDATE job_posts SET category = 'Entertainment'
 WHERE category IS NULL AND id IN (
   '3f0c50dc-4ed7-46e0-ad2a-673ff3b1f18c',
   '927e5be2-968d-4dd4-af10-500b7882116e',
   '990b569d-8913-4f8d-8b35-a70a01451b20',
   '09c75d78-47fe-42b8-a5af-ec0b2ebac7af',
   'c8fc7d02-62bd-4988-9ee2-fe40345c67b3',
   'f32c4554-1906-4088-98c2-b16e1787aaa5'
 );

UPDATE job_posts SET category = 'Food & Beverage'
 WHERE category IS NULL AND id IN (
   '216fcb39-4ba3-457c-a2a4-4434efa27498',
   '179130c8-5ad6-40b4-a2cd-b3a1807900bd',
   '6e88e947-ee25-44c8-a5cd-2ef0e75304fe',
   '033b192b-d835-4853-9bd5-03d86d4a24cc',
   'f68ec8d6-11ea-4a8d-a0ab-fb619597ac6d',
   '9c7b5d8e-4390-4bb5-bf27-be5998fe313e',
   'ad458570-7aaa-4a8b-8b12-510a1dd25302',
   'aaf98317-780d-48a5-946a-0787f8e37570',
   'ebd3a75f-7d5d-40ba-9fea-68ee139c24b1',
   'a99219bc-8166-43a6-abb2-63782000a5b0',
   'c49f944e-5e10-4be6-adc4-1fd0df2639cd',
   '7ea1e12d-506c-4659-a1e3-4bc4f5972248',
   'cb660fb3-9574-42a4-998a-73fe8bfe8c7d',
   'c9436cd6-908b-4501-9529-6b6c1367b5af',
   '8a22f180-ec7f-4e80-8405-c68ada561c08',
   'fd68aff3-ac90-42b9-a27b-ec82ace27ede',
   '809ce7da-537d-4df2-bbc7-07a1f43f4dc0',
   'a98b540e-15c6-4194-afd2-131dee4c108d',
   'bb53bb4a-a548-40c3-b8d2-daf6e939491e',
   '2de6328c-c2fb-49e0-b35c-54daf5c029da',
   '99950d7c-cb90-4ccf-adb7-811781214095',
   '0ea27c38-41ae-4317-b19b-606bbe81a012',
   '344e3a39-30a0-4b85-8ca6-ba129c3fdbaf',
   '2b72760d-c792-40dc-8f4b-31fadf01477b',
   'df24770f-3f08-4966-b784-e06020bec998',
   '8d77eb9b-c6bf-464c-88ee-755014bb943c',
   'e8c3c857-f999-4a12-8353-2bf078564f9d',
   '2d0b5840-4615-4fdc-88a8-24d4b72b6a2d',
   '788a91f8-659b-4492-a238-85bdb9530489',
   'ea689d66-6175-4c60-b1b1-5362ee01a669',
   '4ae87060-5a6a-409d-ab80-ac12678c2c8e',
   '45e73943-04ce-49d0-9fe7-47040cdfe790',
   'e6480f08-8a82-4b85-9a5e-8fd2d837bff6',
   'ae53af58-4d95-476c-b707-8aa8b5d1a9b7',
   '0e4e35cd-be0f-4608-b636-b67306c6b196',
   '8d7407f9-d9a1-467e-94e3-a771d9afaab5',
   '656c0727-a424-4b23-bea5-70a27a39d71c',
   'f972ba90-86ae-4653-8de5-9adbbed88ea5',
   'e400c08b-7187-40db-be4c-2dbc9dd6b868',
   '47da8196-7167-405f-a965-22f981b19b59',
   'a8fdc7c6-b12c-4ace-9aef-820bfd917aa6',
   '2969023a-ff55-4715-8c0e-5cebcddd7eef',
   '63729338-9c5f-4ed2-95d8-d4e223b2b70b',
   '12a56d78-1d28-480d-84c9-b6b615205e35',
   '946068ec-4d38-4078-9298-c76a995f20f5',
   'c2faa47a-2337-4d87-922e-12e4cdfbb2f3',
   '31f17148-80c3-4a1f-8a87-48206b47cc7a',
   'cc4a9910-777e-4fc0-b325-af402b948fca',
   'b0a057a2-771f-4cb4-a910-0dfae2b5e1ba',
   '92a00d23-4560-4101-a887-3e7390d6f6f2',
   '0f75d247-594f-40b6-a3b4-68d843b364a2',
   '0d69d8aa-e758-45df-abcb-2d1969a25316',
   '354b12ea-e670-41d8-ac2f-51d06c1b56c4',
   '0cddb7bb-9965-4f1a-8a7f-310fa1c8e6d3',
   'c43cbe2c-e98e-4449-a7ec-ae9a2898d6c1',
   'c516355f-9073-46dc-979e-ca02b0c53ce5',
   '74cce972-9949-4bdb-ab4c-ceecbfcd969d',
   '9820d3af-5a11-45fc-9c85-281a4a5c45e8',
   'ec119d2b-2d1f-4fa2-aa44-8f602d93b230',
   '3b0f1e6a-a965-44a2-8216-fd1012db24a6',
   'ae1031a5-1823-4481-8cd5-539fc2d70d02',
   '99580bca-0947-4d49-bc44-f2f4fb8ab10c',
   'da140e8c-781f-4cbf-85c2-13697292850f',
   'af7fc045-2581-42d9-948d-5c525a52156d',
   'c58d6ac0-025f-4ef1-a78f-8b47a3ffc6f2',
   'fe26a7fd-4d9c-4676-bf54-ae7f160840f0',
   'c8a775ff-a236-4247-959c-fd62c926b1fc',
   'bc3c6d46-b4b1-43a2-9c7a-9276d0f94bd7',
   'edad8bc3-900e-4d7f-bd86-8f27d1b6cd47',
   '51e6fe49-6c9b-416f-a750-e09bbe821f25',
   '7ea4b75f-56ee-4f49-86b8-0e5d12edf1f6',
   '92ebe3ad-6916-4166-868f-d7285f18107a',
   '0cdfcb0d-243e-4f3a-a97d-bc65e7bc1178',
   'cd389ec2-7b2b-4926-89bd-0ab9b3a0a64d',
   'a1f1c310-d6b3-4301-b9ab-4a474274c8ae',
   '0690f3b7-654b-45a7-81aa-708f2ec31e66',
   'f5393859-b672-4eea-a9f3-fd5ca32035c9',
   '67b392ec-ea89-4b59-9500-dcecaf8d33f9',
   '7e2f215a-ee86-44b3-9977-1643ce32a02e',
   '2cce8c29-bc20-4b4d-b0b5-62949d439392',
   '434c844a-b4fa-4ade-a925-75aaa760717d',
   '78f2eda8-0b87-4ab9-b21e-3a5d43429118',
   '29541cc5-7eab-4a33-a6ef-d5a1b8289aa5',
   '69d5500f-50fd-4717-af04-356bbbe84518',
   '50cf6e2b-b607-4832-a66f-2b7b2de4376e',
   '68b760ca-0a94-4178-a55d-0cb78feeb022',
   '27858aaa-b687-4c2c-a583-cae3559cd8be',
   '4a89bbb0-cc03-44a2-9e78-345cd9fc76d7',
   '9d69443b-0bb4-4a38-ab21-d8e10e3aaca1',
   '3393419d-e130-4364-a66e-1e6d4f686b9c',
   '9359b622-6d67-4107-a62c-5959a975f95c',
   '1334add6-0edb-4be5-8cb4-e2343506f1ac',
   '27f389ab-67c1-45da-a849-dd2c44ad8fdb',
   '92cf2513-131e-4680-b2de-92fae2befce6',
   '8fbdfc75-966d-4db2-9b2a-671ea174d5e5',
   '6093283b-085c-4d7f-a96b-3ae33a7eacd9',
   'e45cf502-149c-4892-871a-b3a1782f600a',
   'd756a2f9-6134-4b59-a673-d54c07ff491f',
   'e0e3b391-5a7f-4d7b-8a16-f15bc46418dd',
   'b95dd493-b5d0-4ef8-ba81-ae14a85c2ae5',
   '43e37331-41a0-4f08-8ccf-5851375dc727',
   '05fc69fb-63ad-43bc-8e36-f2c8d8959e92',
   'f2112ec8-14c1-4368-9c74-71f03f29e850',
   '69ec322d-ee91-429e-b7e1-e6e17cbd7a17',
   'dcdc4851-4c98-4be2-8d37-449dc2fe4458',
   '2603ce94-b199-430b-95fc-90047f91bd7c',
   'b3aca651-ab36-4d0a-80c8-2d791fb85767',
   'ac19ed37-760b-4f04-88d0-42b90c78db19',
   'c6df2f91-ff3a-4715-9a4c-8a0a0fd64bff',
   'afc02a65-0450-4d5c-bb32-8874f950312b',
   'cee2bc81-b4a9-4534-bd80-c31f22cd1bfa',
   '6710b166-9390-4ae2-927c-e620ee825e16',
   'ae1b9d46-8efc-48a3-824d-c9e4731f74dc',
   '25ed9218-f4c1-4dd2-9594-35a9caa8c620',
   'c6b9fcf5-875e-4a2b-8fed-176f4b8da2f3',
   '3c4b7976-83d3-4cd4-9cc8-f5988aa83e9d',
   '88394f4c-5a8f-422c-9437-3a0035be8fb2',
   '3f6f9e38-b080-4124-8fb9-d58eea1d0bf8',
   '8cb32bb7-5e42-4a2a-9d5b-5d7b6b567a63',
   '4f45497f-4e13-4b13-9a93-a2ee6471f325',
   'f02f23e5-e263-4612-a212-e88e43aa2008',
   'a484d89c-8b2f-4549-9492-044ae7d10eac',
   'c2853cb2-4fde-4799-8153-1804022423e9',
   '343da611-7501-433f-9590-aac55e539960',
   '8dff257d-8ddc-46ab-aa84-18b041a243b1',
   'fedf704e-bfd8-4a84-99d3-0d6ecd6fbb26',
   '7807ae2e-88b7-4d62-8fd3-011dfdf6f5d9',
   'bfcfb25b-e7f1-4166-9936-febfb6cf7360',
   '445c1de7-f050-4fce-9789-1981a10607a5',
   'ee0cd152-1db7-4653-b8b4-6bcb5e4605ca',
   '450ad544-5e1f-4a26-9ca5-1713694cbd6d',
   '40f948de-18dc-4ccf-8818-475969cb0313',
   'b8df436a-775c-4146-9382-5ad87df7b714',
   '028e65ca-f281-442d-a43c-ff94de03fcbd',
   'd945272c-7b94-465f-98f0-90ee92c507c2',
   '4b78725e-d479-4350-9fee-d9aeefbe3cc5',
   '01f4c5af-7674-43f0-b183-11d085953439',
   'de8a18c6-75b6-4409-9f5b-001bb535a405',
   '2ba3c799-74ae-497b-ab82-b1ed05213ece',
   '6ee606b1-3a2e-4e7e-9efc-ff01bd994780',
   'd0ddc1d2-21ab-4844-86f4-f8442932dea1',
   '26e55556-539c-4d1a-8440-c2649e912447',
   'c791dda4-7988-4bd8-9ffa-4210bb2ef32a',
   '8f6b8c4d-f2af-40ee-b80f-d8d77f25c9ab',
   'a72d189c-9c3f-4f7b-89e4-6fc1d7a9d8e9',
   '54955b5c-1ab5-43fb-9411-4ad613bf8d3c',
   '0204f856-6fd5-4a22-af2c-9af9e715e7c8',
   '619c6a0c-6547-4cc3-a4ce-93fb5c786426',
   '2e1f412c-1c2a-4f9c-a353-9ec24d8fd0f2',
   '83c19ac2-6980-4da0-b224-185ad5bc3817',
   '0fe18b28-720c-43a3-9b27-c59a57f80ca9',
   '05ee88c9-2720-4057-93af-53c73ab48d82'
 );

UPDATE job_posts SET category = 'Hospitality'
 WHERE category IS NULL AND id IN (
   'a50325ad-2518-4f8d-b397-e23d2ee61596',
   '9bfc82a6-8033-47cf-aa8f-01208eca9888',
   'f528b36d-a76e-40f8-8244-cd9f9b032392',
   'b618c43d-e9e3-41dd-a4b4-5d0807a1eb61',
   'f9e0a600-65ac-4923-89ab-5901cc9fabd5',
   '087093a9-cb33-49ba-b391-210d27cfd352',
   '149c165b-ea6a-4f4e-8905-a3f8b8fce7d6',
   '72e13366-eea9-49b9-9eaf-7c8258d60a1d',
   '9517ba9c-18b2-4ae1-9707-bda171c56465',
   'e138eb6d-0d30-4210-8688-1b94f8f9d83f',
   '8d69a200-d1ff-4f9e-b58a-bcb83402fbb1',
   'eb7dc7f0-b2ba-4289-94e0-246ce1091ba8',
   '67a8b0ff-83ce-4589-b3d1-56ef2744f4d3',
   '144be43f-fb18-4741-b8f9-6ccfd6c8da67',
   '1f43a83d-51fe-4220-8f1e-2e9a9d0640f6',
   'ef9360b6-51a1-4561-8760-1c3a4bca211e',
   'dd170938-2005-4fba-aba1-f9accbe168f5',
   '9fb70149-8220-4748-82c0-223e860a5a5e',
   '9130fe4f-ba1d-488b-97c2-0b1fffd7ce87',
   '9d906957-9992-4cd3-99f5-14c6e7131ae6',
   '306621f8-ca9f-4768-886d-ddeaf5460257',
   'd8c20441-bdba-4baa-9963-921ff7a88a54',
   '7644a406-90c6-4ff3-a158-89730676e87a',
   'ba02fe20-6c2d-48f8-a614-b5512d5c0cd7',
   '214c93f0-61bd-44da-b934-d334ad2496cc',
   'ba37002b-3cd9-4e86-990d-dd0e3debdc15',
   '4f266d33-95e7-4f45-bd3d-d6e69ac05045',
   '85c604c9-9fa3-4d6c-8328-4747dbe3e6b2',
   'a4f3f24a-3279-4e10-862f-f3187f9abc17',
   'b6854da2-07fe-4b02-a493-f46cc5052bf8',
   'a03ccca3-cbd9-4e4d-a7fe-f75aaa56b2bf',
   '3d722c70-1592-4313-aeee-c9e23737d674',
   '51b019be-8a6d-4d0a-b7b7-2f95811c0d0c',
   '9480f75e-4c1f-4953-bd88-287d66fbffaa',
   'ca7b8d3a-a7b0-4b21-99a2-202143accb38',
   'fbd76f55-f883-41d0-a5de-c11b656b10fc',
   'c5ac254c-a418-48de-bd1e-d44bdb8ac6a5',
   '6f86a844-3cd2-4260-a42e-44953b9c0e9c',
   'c20af50f-5cad-4787-88f0-db76fb1db2e6',
   'ef27ef3f-bd78-4f88-ad26-7c01220d37b5',
   'c20d8725-6ddf-443b-8337-b3b0f1c8c628',
   '8450bb8e-1f06-496f-8609-3529276527eb'
 );

UPDATE job_posts SET category = 'Housekeeping'
 WHERE category IS NULL AND id IN (
   '59db6dda-4d2c-4d6e-bcd2-481f48c48f89',
   'ca71ec2a-83b2-4c6f-bd9b-ef67a70cd6e6',
   '60245780-96f5-4067-a021-1049e7239f61',
   '8be22058-a88e-46dd-b81f-0da4d5de07e2',
   'dfdc2cec-390d-455e-87c3-b072f45cd6eb',
   '6e77edbd-055d-428f-86ae-940551a81767',
   '85875f3d-971c-4461-8753-1c05e91e4696',
   '573776bb-e2fe-414a-bca9-0ac87dab387b',
   '444312c7-c4b8-408f-af5b-6bae90cc9800',
   '7e94a0dd-dcdc-4db1-9a83-544c02a980d0',
   'd1ff4387-244a-40fc-aa57-035f9e71b1fe',
   'd0a14345-7a86-4006-9b41-a0af55d4abd5',
   '44b4608d-e9a1-4b7f-88a8-510e2e742891',
   '1df7559d-dd4a-4c98-bb9e-40a206621336',
   'd69650ed-4b52-4007-bdd4-79b6dd6f5f24',
   '345ac0e8-5915-4f34-90cb-b905616083e4',
   '9c3c39f5-0319-4e15-8575-593885a73430',
   '483b9498-afbe-4d87-80a7-d7e0523332ab',
   'f9852f4f-5cf2-4273-94fc-1895e6a28142',
   '12d94722-3a03-4c42-b895-5fd97dad41eb',
   'def7ec35-be00-42fb-a013-8c741a4da4f1',
   '2a9df697-0ba0-479c-bfa0-e9e21463e90f',
   'ab77d53a-dbd0-4d08-b581-6dc6f5a0794c',
   '2174a941-7350-4f4a-8aa4-b00471a98755',
   '98d54938-54e6-4d3c-a5fc-e3c52d176e02',
   'e0f5157a-0d46-4cd9-824e-077eac67784b',
   'ca6d1a61-a8b7-4613-af24-8ef64bdd81b4',
   'e0f99061-3a55-4197-ba99-cf2b8fb3db4f',
   'c628d156-a3d0-4369-9508-dcfc7ab502ff',
   '78ad41b0-5df1-4c7c-82ee-55a9823de103',
   '3bbff1d9-8d38-43be-a814-7eae764830e0',
   'a98b17f1-d0fb-4f31-9016-21f9f8421933',
   'b8ed3c05-da8d-4bc7-9d45-10110c85d727'
 );

UPDATE job_posts SET category = 'Lift Operations'
 WHERE category IS NULL AND id IN (
   'd647bb42-db82-45e5-9853-7e79815aa904'
 );

UPDATE job_posts SET category = 'Maintenance'
 WHERE category IS NULL AND id IN (
   '2ebef780-9be2-4b3c-b05e-99d0340d91e7',
   '25aad515-25c4-4867-b8f6-57c5d563543e',
   '7b8a6f12-8ea9-4ba0-a8d8-2927e01d8756',
   '509510f3-8c90-44e4-9248-779e1b397983',
   '94cd926d-7108-4af1-8c60-aeff4c9af8d3',
   '8a03995b-6d7a-44c4-b339-56b383222efc',
   '49f70338-0aad-4975-91d6-8c729887bae2',
   '944862fb-28ae-4f20-a097-19e1820a9e3d',
   '4206d535-8c35-4dad-8b1c-5d60988b421b',
   'deb35ad2-4f55-418f-bb57-6817a81a7e85',
   '109b82f4-8ba4-4451-baba-df8e427006a2',
   '33b7e597-b1c5-47d4-97dc-4a5d68e79619',
   '8c00065b-c6f2-422f-a342-874ad0f3df3a',
   '4ca499ec-6633-4072-a6e1-76e2e7a7474c',
   '4dd219cc-dd4d-42e0-b5e1-455a94233ae9',
   '7ea7672f-05b9-49ed-a58d-54322122c803',
   'e6918aa5-1c1d-447b-8d29-fbfb5ee6bdc2',
   '3d95c13c-cc99-4cec-97af-5bef1dceb47d',
   '02b41bca-ccf3-4c81-b2da-2f2d9913cafc',
   'd72d7ee9-d878-4642-8ceb-8bba7714ebf3',
   'be25b7eb-365b-456c-92e7-5f14c7997ee0',
   '0c7e00f1-31bd-412c-ac4b-87bec1fab130',
   'd0e7758e-7a50-460b-a6dc-d5c68d7eba70',
   'a64b58c7-4b9b-4fa1-9cdc-0d063db1dc68',
   '7a1ca0e7-5d88-4f5a-8ef1-89a8d642df30',
   'c8f19b0e-ff54-4b3a-82ec-c97c17adc149',
   '1bf93b52-32be-462a-a667-6d3c7fb37dab',
   '7bbb3711-7671-4cee-85cc-7eefcab30b8e',
   'cd949215-a5e2-4aff-b7ce-524005d7348f',
   '092942f3-b27d-47cf-ad62-887333122b82',
   'f6cbfad2-75c5-4a96-a788-6e7acfe3bf82',
   'a6c32fe8-613d-424d-9557-9699ce9c53e0',
   '180092c4-8588-4d42-86f4-9c355d60127a',
   '0c02f160-33d5-4242-bc3f-0878be6ebf55',
   '6d1416ab-0543-4bb4-bed3-37e5512c4b43',
   '6fc33a9e-651c-474d-aa0d-b34fd7aadf9c',
   '44e9613a-471d-4327-99ab-118c1efd8668',
   'd6ba2717-18e7-4bfb-b3c5-1d34de892170',
   '7db5ad03-6867-444d-a24d-1d42fbc9c63f',
   'b8f980e1-3127-45bc-a82c-780ab6879432'
 );

UPDATE job_posts SET category = 'Resort Operations'
 WHERE category IS NULL AND id IN (
   '548d1142-8549-456c-8e06-6825b3ee62c5',
   'ca661b8a-57a2-446a-bc5a-8f6f78bb4a1c',
   'b7f7ff71-9c01-452f-b3ac-659ac37b9ea9',
   '7451b3b3-e83d-44b8-bb9a-d1e95e564ed1',
   'd0f84e61-1def-423e-ade0-29ae61cc3d47',
   'adcd588f-bb25-460e-8410-91f7edea320c',
   '39e4209f-584d-45cc-9ef5-375bba445db4',
   '8e46c613-6eca-4f80-8858-aad77899f2d5',
   'eb6898a1-d83d-4650-a21a-1ec1a11f4765',
   '0fb589f1-44ee-428a-a329-a025df337a31',
   'a16abdea-093d-4e61-948c-f531649aa474',
   '00c2a7c1-84ed-4a14-9910-cea3590fb2bf',
   '4d3f1780-ce6e-4532-8e88-afae8e242e0e',
   'c971cbb3-dfec-42ea-b827-a722222022fe',
   '27fb5915-82f1-47d6-a847-ad2f0c82711e',
   'dc257b19-2c98-4384-8711-93f0657d87d6',
   'da4f456b-a1ce-4cff-8baf-3defa45e50e9',
   'b5ad3ffb-412a-4885-bec0-a1009c73124e',
   'd5c12747-c213-43be-9c30-0a96af15fd92',
   '3ca77a1a-5836-4f73-8953-79c7e1aacacd',
   '1b2ac2d7-62c2-4957-b02e-60be41c5ed88',
   '68f5ab89-9191-49bb-a511-767309f47d18',
   'b2f477a1-969c-4805-8cfc-27fd76531f17',
   '078239e8-702c-47a4-b5de-d1dddc06905e',
   'b5270378-3bf3-4014-999b-a8d32e61ea28',
   '510e240a-5c38-469f-afe9-83ed237c17e8',
   '1a5cc4db-8e07-49cd-8f1c-463c85a35b87',
   'c9e82ab8-437f-4e82-abee-0eed1c80d910',
   'e6a1090a-1790-4811-bd07-b3b3c422d47f',
   '90574039-10a0-4f9a-99cb-af923f7e3155'
 );

UPDATE job_posts SET category = 'Retail'
 WHERE category IS NULL AND id IN (
   'bc44f2d3-f4fa-4932-953d-d20efac00b30',
   'fdee8571-0b40-44d7-a34b-e6d762e151cb',
   '5fc5885e-54dc-4a33-8606-8ba3d8a888a1',
   '2ff5111b-a6c3-43f9-b87f-2105d700422a',
   'a748b5ba-55b8-4fbe-81f7-ac283aa741c3',
   'f057acd2-2f02-448f-8689-ae290fc76278',
   '700d0186-48b8-4924-b541-3e9482b74f7a',
   '390cce67-00e7-493b-b60a-1da6eb7dae31',
   '5b1efb3a-1fe9-4243-b855-47e7d54faf8d',
   'd91b2d72-0471-418a-832c-d89cca803695',
   'a85d8a74-3490-4e6f-a2eb-8adde0662a5f',
   '8a891496-dd64-40c5-967a-0765de3042f6',
   '7fb903fd-c535-451c-9724-c9a7cd73ce2c',
   'd26d150c-e4e4-4573-bc5a-0f3c933f987a',
   '441a13ab-622e-439a-bc02-757c3fbaad19',
   '0da53468-609c-468f-9fa1-3563c2914e3c',
   'ab6dca58-d4ea-4c2a-9e9a-4669688c9aed',
   'fc3aabc7-459d-4225-b64e-0c8bb109eb33',
   'a042c39f-2c7b-41a7-8e18-ebb7990c013d',
   '7090124a-65ef-4210-8eec-334f6f845c73',
   '0b92c85a-9109-4bca-bd16-ff376a626aab',
   '407b4134-2263-47ae-bb3b-85bb2818ee7b'
 );

UPDATE job_posts SET category = 'Ski Instruction'
 WHERE category IS NULL AND id IN (
   'a45ad374-3533-4e5e-818f-16f84d7be149',
   '699c6dc3-8ac3-4556-9138-080228afda2f',
   '6d04e375-c3f3-46fb-99ca-f000eae9a90e',
   '3e0c3f72-e004-44a3-ab93-b4bbf8ebe597',
   'b4aa4bf8-d079-4f49-a60a-0934480f4cb5',
   '42ece98e-8e4d-4e26-a531-28e073a84ad6',
   '4dab1483-39c1-4100-aec3-9d99944bc330',
   'ad3d998d-fef9-4a3a-b75c-045d9e45ce7b',
   'c7d61f47-e499-4385-b733-8ccbd5d31bf3',
   '1f9bcc8d-1132-443d-82b5-ac3cef2b5309',
   'd43d6418-5fbf-4ada-a1a6-924dc9d2b82e',
   '581f76f3-e78e-4549-b859-9dbf97309c7c',
   '2f5eb4d7-977d-40f3-ad1e-982b251aa0a8',
   'c9f08d71-8194-4820-bf40-b8fb8fbaf0ea',
   'cd513099-3fe1-4b67-80cc-ff898cb117da'
 );

-- ── verify ───────────────────────────────────────────────────────────────
DO $$
DECLARE
  overwritten int;
  bad_value   int;
  still_null  int;
  titles_moved int;
BEGIN
  -- Nothing that already had a category may have changed.
  SELECT count(*) INTO overwritten
    FROM job_posts j JOIN _cat_before b ON b.id = j.id
   WHERE b.category IS NOT NULL AND j.category IS DISTINCT FROM b.category;
  IF overwritten > 0 THEN
    RAISE EXCEPTION '% rows had an existing category overwritten', overwritten;
  END IF;

  -- Only the agreed vocabulary. A typo here would be invisible until a
  -- worker filtered for a category that matches nothing.
  SELECT count(*) INTO bad_value FROM job_posts
   WHERE category IS NOT NULL
     AND category NOT IN ('Ski Instruction','Hospitality','Food & Beverage','Retail',
                          'Resort Operations','Lift Operations','Housekeeping',
                          'Maintenance','Administration','Entertainment','Other');
  IF bad_value > 0 THEN
    RAISE EXCEPTION '% rows carry a category outside JOB_CATEGORIES', bad_value;
  END IF;

  -- No title may have been touched; this migration only labels.
  SELECT count(*) INTO titles_moved
    FROM job_posts j JOIN _cat_before b ON b.id = j.id
   WHERE j.title IS DISTINCT FROM b.title;
  IF titles_moved > 0 THEN
    RAISE EXCEPTION '% titles changed — this migration must only set category', titles_moved;
  END IF;

  SELECT count(*) INTO still_null FROM job_posts WHERE category IS NULL;
  RAISE NOTICE 'category backfilled; % rows remain unclassified by design', still_null;
END $$;

COMMIT;
